---

# Install packages
- name: add official MariaDB apt key
  apt_key: url={{ mariadb_repo_key_url }} state=present
  when: mariadb_set_repository

- name: setup official MariaDB repository
  apt_repository: repo="{{mariadb_repo}}" state=present update_cache=yes
  when: mariadb_set_repository

- name: installing MariaDB packages
  apt:
    name: ['{{ mariadb_package_client }}', '{{ mariadb_package_server }}', 'python-mysqldb']
    state: present
    update_cache: yes
  notify: stop mariadb

- name: installing MariaDB tools
  apt:
    name: ['mysqltuner', 'percona-toolkit']
    state: present
    update_cache: yes
  when: mariadb_install_tools
  tags: [mysql-tools]
